version: "3"
services:
  postgres:
    build:
      context: .
      dockerfile: ./config/Dockerfile
    restart: always
    ports:
      - "5450:5450"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=zilla
      - PGPORT=5450
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db: null