version: "3"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5450:5450"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=zilla
      - PGPORT=5450